//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Frontendnetworkpanel_prefab
    {
        public const string BundleName = "frontendnetworkpanel_prefab";
        public const string FRONTENDNETWORKPANEL = "FrontendNetworkPanel";
    }
}
