//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Frontendnetworkpanel_prefab
    {
        public const string BundleName = "frontendnetworkpanel_prefab";
        public const string FRONTENDNETWORKPANEL = "FrontendNetworkPanel";
    }
    public class Gameobjectactor
    {
        public const string BundleName = "gameobjectactor";
        public const string ASSULTSHIPMESH_LOCAL = "AssultShipMesh_Local";
        public const string ASSULTSHIPMESH_REMOTE = "AssultShipMesh_Remote";
        public const string FANLINE = "FanLine";
        public const string MARCOSHELL_LOCAL = "MarcoShell_Local";
        public const string MARCOSHELL_REMOTE = "MarcoShell_Remote";
        public const string TOMATOSHOTEXPLODE_LOCAL = "TomatoShotExplode_Local";
        public const string TOMATOSHOTEXPLODE_REMOTE = "TomatoShotExplode_Remote";
        public const string TOMATOSHOTTRAIL_LOCAL = "TomatoShotTrail_Local";
    }
}
